namespace Drac
{
    enum TokenCategory
    {

        AND,
        BRACKET_OPEN,
        BRACKET_CLOSE,
        BREAK,
        CHAR_LITERAL,
        DEC,        
        DIV,
        DO,
        ELIF,
        ELSE,
        EQUALS,
        FALSE,
        IDENTIFIER,
        IF,
        INC,
        INT_LITERAL,
        LESS,
        LESS_EQUAL,
        MAIN,
        MORE,
        MORE_EQUAL,
        MUL,
        MULTI_COMMENT,
        NOT,
        NEG,
        OR,
        PARENTHESIS_OPEN,
        PARENTHESIS_CLOSE,
        PLUS,
        REMAINDER,
        RETURN,
        STRING_LITERAL,
        SQUARE_BRACKET_OPEN,
        SQUARE_BRACKET_CLOSE,
        TRUE,
        VAR,
        WHILE,
    }

}